//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.email_templates = new HashSet<email_templates>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string active { get; set; }
        public string reset_hour { get; set; }
        public string next_reset_time { get; set; }
        public string daily_limit { get; set; }
        public string limit_d0 { get; set; }
        public string limit_d1 { get; set; }
        public string limit_d2 { get; set; }
        public string limit_d3 { get; set; }
        public string limit_d4 { get; set; }
        public string limit_d5 { get; set; }
        public string limit_d6 { get; set; }
        public string leads_today { get; set; }
        public string max_age { get; set; }
        public string min_downpayment { get; set; }
        public string email_list { get; set; }
        public string credits { get; set; }
        public string cutoff_amount { get; set; }
        public string cutoff_mode { get; set; }
        public string intro_enabled { get; set; }
        public string intro_from { get; set; }
        public string intro_subject { get; set; }
        public string intro_body { get; set; }
        public string intro_bcc { get; set; }
        public string auto_crpost_exclude { get; set; }
        public string trickle_campaign_exclude { get; set; }
        public string hubspot_exclude { get; set; }
        public string grade_filter { get; set; }
        public string expanded_search_credit_repair { get; set; }
        public string expanded_start_hour { get; set; }
        public string expanded_end_hour { get; set; }
        public string expanded_timezone { get; set; }
        public string consume_ascent_rejects_only { get; set; }
        public bool currentflag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email_templates> email_templates { get; set; }
    }
}
