//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_templates
    {
        public int emailid { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string html { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> client_id { get; set; }
        public string credit { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> enable_modified { get; set; }
    
        public virtual client client { get; set; }

        public string toemail { get; set; }
    }
}
