//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead_counts
    {
        public int id { get; set; }
        public string Client { get; set; }
        public Nullable<int> ex { get; set; }
        public Nullable<int> gd { get; set; }
        public Nullable<int> sp { get; set; }
        public Nullable<int> mp { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> sc { get; set; }
    }
}
