//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myfhalead
    {
        public string id { get; set; }
        public string status { get; set; }
        public string state_id { get; set; }
        public string create_time { get; set; }
        public string ip { get; set; }
        public string hubspot_cookie { get; set; }
        public string hubspot_posted { get; set; }
        public string site { get; set; }
        public string client_id { get; set; }
        public string sold_time { get; set; }
        public string free { get; set; }
        public string cam_step { get; set; }
        public string cam_due { get; set; }
        public string cam_last_email_time { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string loantype { get; set; }
        public string proptype { get; set; }
        public string loanamount { get; set; }
        public string inttype { get; set; }
        public string spechome { get; set; }
        public string propstate { get; set; }
        public string downpayment { get; set; }
        public string value { get; set; }
        public string balance { get; set; }
        public string rate { get; set; }
        public string workphone { get; set; }
        public string homephone { get; set; }
        public string cellphone { get; set; }
        public string email { get; set; }
        public string calltime { get; set; }
        public string credit { get; set; }
        public string notes { get; set; }
        public string srlp { get; set; }
        public string hash { get; set; }
        public string trusted_form_url { get; set; }
        public string grade { get; set; }
        public string expanded_search_credit_repair { get; set; }
        public string householdincome { get; set; }
        public string sr_token { get; set; }
        public bool bounced { get; set; }
    }
}
