//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myfhabackendEntities : DbContext
    {
        public myfhabackendEntities()
            : base("name=myfhabackendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<email_templates> email_templates { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<myfhalead> myfhaleads { get; set; }
        public virtual DbSet<template_client> template_client { get; set; }
        public virtual DbSet<report_view> report_view { get; set; }
        public virtual DbSet<sentlog> sentlogs { get; set; }
        public virtual DbSet<lead_counts> lead_counts { get; set; }
    }
}
