//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myfhaemailadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_view
    {
        public int emailid { get; set; }
        public string Client { get; set; }
        public string subject { get; set; }
        public int cnt_24_Hours { get; set; }
        public int cnt_7_Days { get; set; }
        public int cnt_1_Month { get; set; }
        public int cnt_6_Months { get; set; }
        public int Total { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> enable_modified { get; set; }
    }
}
